/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penampilgambar;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import mainmenu.MainMenu;

/**
 *
 * @author acer
 */
public class PenampilGambarUndecorated extends javax.swing.JFrame {

    /**
     * Creates new form PenampilGambar
     */
    public PenampilGambarUndecorated() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        gambar1Button = new javax.swing.JButton();
        gambar2Button = new javax.swing.JButton();
        gambar3Button = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        primitive = new javax.swing.JLabel();
        elemental = new javax.swing.JLabel();
        emotional = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        buttonPanel.setBackground(new java.awt.Color(255, 255, 255));

        gambar1Button.setText("Gambar 1");
        gambar1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gambar1ButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(gambar1Button);

        gambar2Button.setText("Gambar 2");
        gambar2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gambar2ButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(gambar2Button);

        gambar3Button.setText("Gambar 3");
        gambar3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gambar3ButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(gambar3Button);

        exitButton.setText("Keluar");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(exitButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setBackground(new java.awt.Color(255, 255, 255));
        imagePanel.setLayout(new java.awt.CardLayout());

        primitive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penampilgambar/primitive_dragon_by_markolios_def6zni-fullview.png"))); // NOI18N
        imagePanel.add(primitive, "0");

        elemental.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penampilgambar/elemental_dragon_by_markolios_def6zsm-fullview.png"))); // NOI18N
        imagePanel.add(elemental, "1");

        emotional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penampilgambar/emotional_dragon_by_markolios_dejuznd-fullview.png"))); // NOI18N
        imagePanel.add(emotional, "2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(618, 845));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gambar1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gambar1ButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "0");
    }//GEN-LAST:event_gambar1ButtonActionPerformed

    private void gambar2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gambar2ButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "1");
    }//GEN-LAST:event_gambar2ButtonActionPerformed

    private void gambar3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gambar3ButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "2");
    }//GEN-LAST:event_gambar3ButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        new MainMenu().setVisible(true);
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarUndecorated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarUndecorated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarUndecorated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarUndecorated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PenampilGambarUndecorated().setVisible(true);
                
                PenampilGambarUndecorated fullFrame = new PenampilGambarUndecorated();
                
                GraphicsDevice device = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                
                fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel elemental;
    private javax.swing.JLabel emotional;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton gambar1Button;
    private javax.swing.JButton gambar2Button;
    private javax.swing.JButton gambar3Button;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel primitive;
    // End of variables declaration//GEN-END:variables
}
